######################################################################
# Automatically generated by qmake (2.01a) ? 11? 30 00:52:40 2009
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += EthernetConnectionWidget.h
FORMS += EthernetConnectionWidgetForm.ui
SOURCES += EthernetConnectionWidget.cpp main.cpp
